parameters:
#    tnk_user.example.class: TNK\Bundle\UserBundle\Example

services:
#    tnk_user.example:
#        class: %tnk_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
