parameters:
#    tnk_blog.example.class: TNK\Bundle\BlogBundle\Example

services:
#    tnk_blog.example:
#        class: %tnk_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
