parameters:
#    tnk_admin.example.class: TNK\Bundle\AdminBundle\Example

services:
#    tnk_admin.example:
#        class: %tnk_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
