<?php

namespace TNK\Bundle\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findLastPubLished()
	{
		$qb = $this->createQueryBuilder('a');

	    $qb->orderBy('a.datePublication', 'DESC')
		   ->setMaxResults( 1 );
	
	    return $qb->getQuery()->getSingleResult();
	}

	public function findAllOrdered()
	{
		$qb = $this->createQueryBuilder('a');

	    $qb->orderBy('a.datePublication', 'DESC');
	
	    return $qb->getQuery()->getResult();
	}
}
